export enum Controllers {
    MAIN = 'Main',
    CLIENT = 'Client',
    USER = 'User',
    ENUMERATION = 'EnumerationModel',
    PARTNER = 'Partner',
    REGION = 'Region',
    CONTENT = 'Content',
    REPORT = 'Report',
    DASHBOARD = 'Dashboard',
    PAYMENT = 'PaymentSystem',
    BONUS = 'Bonus',
    BET_SHOP = 'BetShop',
    PRODUCT = 'Product',
    PERMISSION = 'Permission',
    CURRENCY = 'Currency',
    BASE = 'Base',
    UTIL = 'Util',
    LANGUAGE = 'Language',
    PROVIDER = 'Provider',
    AFFILIATES = 'Affiliate',
    AGENT = 'Agent',
}

export enum PBControllers {
  ROUND = 'Round',
  REPORT = 'report',
  PARTNERS = 'partners',
  COMMON = 'common',
  CMS = 'cms',
}
